// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyNlMtqPwAVDsNLHHCYDWRxh8JdqNgOvc',
    appId: '1:978197217398:web:03d6ceb4013ead04fb5f57',
    messagingSenderId: '978197217398',
    projectId: 'fieldsync-47289',
    authDomain: 'fieldsync-47289.firebaseapp.com',
    storageBucket: 'fieldsync-47289.firebasestorage.app',
    measurementId: 'G-L2JKDNL76H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ8sdE7zjgeZsSQFeyBLkffo4FsinSDh4',
    appId: '1:978197217398:android:dbb50068e50fffb0fb5f57',
    messagingSenderId: '978197217398',
    projectId: 'fieldsync-47289',
    storageBucket: 'fieldsync-47289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcYqzBUi4tNleMXCt_CYsIRWqV1lUDf4',
    appId: '1:978197217398:ios:495f907fa0e45525fb5f57',
    messagingSenderId: '978197217398',
    projectId: 'fieldsync-47289',
    storageBucket: 'fieldsync-47289.firebasestorage.app',
    iosBundleId: 'com.example.fieldsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcYqzBUi4tNleMXCt_CYsIRWqV1lUDf4',
    appId: '1:978197217398:ios:495f907fa0e45525fb5f57',
    messagingSenderId: '978197217398',
    projectId: 'fieldsync-47289',
    storageBucket: 'fieldsync-47289.firebasestorage.app',
    iosBundleId: 'com.example.fieldsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyNlMtqPwAVDsNLHHCYDWRxh8JdqNgOvc',
    appId: '1:978197217398:web:ce58ae97459fa3b9fb5f57',
    messagingSenderId: '978197217398',
    projectId: 'fieldsync-47289',
    authDomain: 'fieldsync-47289.firebaseapp.com',
    storageBucket: 'fieldsync-47289.firebasestorage.app',
    measurementId: 'G-5NVY7SQQDL',
  );
}
